### ISSUE TITLE
Definition for rule 'nodeca/indent' was not found.

### ISSUE THREAD

**Issue by cheshirecatalyst** [icemobilelab/virgilio#52]
Tested in v0.10.35 and v0.11.15:

While I often use gulp, I don't use eslint, (still using jshint, as our team uses a base config for atom editor that we share for indent purposes) . Anyway, I have tried installing eslint and the plugin for indent globally, as well as locally through `npm i`, to no avail. My first guess is that gulp-eslint is not picking up the  nodeca plugin, simply because when I run my global eslint against the .eslintrc I get no such error.

So as I am unfamiliar with this particular configuration for linting, can I get someone else to confirm with a fresh clone of this repo.

**Comment by jwoudenberg** [comment]
Interesting, I don't have this problem but I heard of others who do. Could you please try updating to gulp-eslint 0.2.2 and see if that fixes the problem?

You say running eslint globally doesn't give you any issues. Do you have the nodeca plugin installed as a global npm package as well?

**Comment by cheshirecatalyst** [comment]
gulp-eslint is referenced in the package.json as `"gulp-eslint": "^0.2.0"` and as such is currently installed @ 0.2.2 .

Yes I installed the nodeca plugin globally after trying it locally through the `npm i`.

**Comment by cheshirecatalyst** [comment]
From a tangental design point, since some people are having trouble, why isn't jshint being used frozen @  2.4.x, until it can be confirmed that eslint + gulp works with the indent problem for %100 of users. I only ask because i am working on a pull request, fixing a deprecated package `gulp-example-to-test` which has moved to a different package name, and adding local gulp to the package, since out of the box the tests wont run without a local gulp.

I would like to go ahead and submit it, but since the tests won't run in the framework as is due to eslint, i am unable to verify I have introduced non breaking changes, with regard to the `gulp-example-to-test` package.

**Comment by jwoudenberg** [comment]
@cheshirecatalyst, the reason is that as far as I knew, things worked. You are right that it shouldn't affect development.

I worked around the issue by removing the plugin for now. I'll keep this issue open until we have found a neater solution.

**Comment by cheshirecatalyst** [comment]
This worked.
