### ISSUE TITLE
The example has a bug

### ISSUE THREAD

**Issue by frunjik** [icemobilelab/virgilio#58]
Virgilio = require('virgilio');
var virgilio = new Virgilio();
virgilio.namespace$('number').defineAction$(function add(num1, num2) {
    return num1 + num2;
});

//The example uses Virgilio (the module) not the object ...
virgilio.number.add(3, 6).then(function(result) {
    console.log(result);    //=> 9
});

**Comment by NinjaTux** [comment]
fixed with your pull request!
